title: Proyect148980
description: >-
  Esto es para manosear un poco esta pagina, asi que tratare de inventar
  cualesquiera cosas que se me ocurrir. 
template:
  repo: proyect148980-template
  name: proyect148980
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
